include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    avoid_empty_export_declarations: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    empty_catches: true
    empty_constructor_bodies: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    no_runtimeTypeToString: true
    noop_primitive_operations: true
    only_throw_errors: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors_in_immutables: true
    prefer_contains: true
    prefer_constructors_with_required_for_final_fields: true
    prefer_conditional_export_imports: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_enum_to_string_map: true
    prefer_equal_for_hash_code_and_hash: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_parameters: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_if_null_operators: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty_is_not_empty: true
    prefer_is_not_empty: true
    prefer_iterable_where: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    recursive_getters: true
    require_trailing_commas: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finalizers: true
    type_annotate_new_handlers: true
    unawaited_futures: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true